version: '3.7'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
  language_tool:
    container_name: language_tool
    build:
      context: ./language_tool
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - REACT_APP_URL=http://14.199.43.160:3000
      - REACT_APP_WEB_API_URL=http://14.199.43.160:5000
      - REACT_APP_LANG_CHECK_API_URL=http://14.199.43.160:8081

volumes:
  mongodb_data_container: