version: '3.7'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      - TZ=Asia/Hong_Kong
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=xaUBJZbG5v{W*[{&
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db
  backend:
    container_name: backend
    environment:
      - TZ=Asia/Hong_Kong
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    command: /usr/local/bin/gunicorn -w 8 -b :5000 backend:api
  language_tool:
    container_name: language_tool
    build:
      context: ./language_tool
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '80:80'

volumes:
  mongodb_data_container:
